apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: dbaas-operator-controller-manager-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
    type: dbaas-operator
status:
  loadBalancer: {}
