
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
    type: dbaas-operator
