# permissions for end users to edit dbaasconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasconfig-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconfigs/status
  verbs:
  - get
