# allow users to view inventories in the installation namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbaasinventory-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbaasinventory-viewer-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated