apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/osd-addons/dbaas-operator-index@sha256:83649d689a88763cd2c9e22090af4c9d006deed2d2a6f4ed0a9373811734b1b9
  displayName: Red Hat OpenShift Database Access
