apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInventory
metadata:
  name: inventory-example
spec:
  credentialsRef:
    name: dbaas-vendor-credentials
  providerRef:
    name: provider-example-registration
