apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInstance
metadata:
  name: dbaasinstance-sample
spec:
  inventoryRef:
    namespace: openshift-dbaas-operator
    name: inventory-example
  name: my-cluster-free
  cloudProvider: AWS
  cloudRegion: US_EAST_1
