apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ecosystem-appeng/dbaas-operator-catalog:v0.5.0
  displayName: DBaaS Operator

---
apiVersion: v1
kind: Namespace
metadata:
 name: openshift-dbaas-operator

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dbaas-operator-group
  namespace: openshift-dbaas-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dbaas-operator
  namespace: openshift-dbaas-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dbaas-operator
  source: dbaas-operator
  sourceNamespace: openshift-marketplace
  config:
  startingCSV: dbaas-operator.v0.5.0
