apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/tchughesiv/dbaas-operator-summit-catalog:v0.4.0-cd9f4ba.plugin-0.4.0
  displayName: DBaaS Operator

---
apiVersion: v1
kind: Namespace
metadata:
 name: openshift-dbaas-operator

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dbaas-operator-group
  namespace: openshift-dbaas-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dbaas-operator
  namespace: openshift-dbaas-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dbaas-operator
  source: dbaas-operator
  sourceNamespace: openshift-marketplace
  startingCSV: dbaas-operator.v0.4.0-cd9f4ba.plugin-0.4.0
