name: Push Image

on:
  push:
    branches:
    - main
    - release-*
    tags:
      - '*'

env:
  IMAGE_TAG_BASE: quay.io/ecosystem-appeng/dbaas-operator-dev

jobs:
  push:
    if: github.repository == 'RHEcosystemAppEng/dbaas-operator'
    runs-on: ubuntu-latest
    environment: quay push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Log in to image registry
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: quay.io

    - name: Build and push release
      run: IMAGE_TAG_BASE=${{ env.IMAGE_TAG_BASE }} CONTAINER_ENGINE=podman DEV=true make release-build release-push

    - name: Retrieve version
      run: echo "::set-output name=VERSION::$(DEV=true make get-version)"
      id: version

    - name: Print image url
      run: |
        echo "Image pushed to ${{ env.IMAGE_TAG_BASE }}:v${{ steps.version.outputs.VERSION }}"
        echo "Bundle pushed to ${{ env.IMAGE_TAG_BASE }}-bundle:v${{ steps.version.outputs.VERSION }}"
        echo "Catalog pushed to ${{ env.IMAGE_TAG_BASE }}-catalog:v${{ steps.version.outputs.VERSION }}"
