name: Build Image

on:
  pull_request:
    branches:
    - main
    - release-*

env:
  REGISTRY: quay.io
  REGISTRY_ORG: tchughesiv

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "quay push"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Image build
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: dbaas-operator
        platforms: linux/amd64
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Log in to ${{ env.REGISTRY }}
      uses: redhat-actions/podman-login@v1
      id: quay-login
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.REGISTRY }}

    - name: Image push
      uses: redhat-actions/push-to-registry@v2
      id: push-to-quay
      with:
        registry: ${{ env.REGISTRY }}/${{ env.REGISTRY_ORG }}
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
